spring:
  application:
    name: beautiful-care
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://turntable.proxy.rlwy.net:43838/railway
    username: root
    password: uFTsQCoEcvOYPLfRRanvGDzVRzqDPvsb
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: UTC
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        id:
          new_generator_mappings: true
          db_structure_naming_strategy: legacy
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/,file:./uploads/
      cache:
        period: 3600

# Cấu hình lưu trữ file
file:
  uploadDir: ./uploads/images
  # Cấu hình WebP
  webp:
    enabled: true
    quality: 0.85  # Chất lượng ảnh WebP (0.0-1.0)
  # Cấu hình cache
  cache:
    max-age: 604800  # 7 ngày (tính bằng giây)
    public: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 24 hours
      refresh-token:
        expiration: 604800000 # 7 days

# Cấu hình Swagger UI
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    filter: true
    disable-swagger-default-url: true
    display-request-duration: true

# Cấu hình logging
logging:
  level:
    root: INFO
    com.dailycodework.beautifulcare: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
